/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#0057c2',
        'primary-container': '#006ef2',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#afc6ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001a43',
        'on-primary-fixed-variant': '#004398',
        'on-primary-container': '#fefcff',
        'secondary': '#536069',
        'secondary-container': '#d6e4ef',
        'secondary-fixed': '#d6e4ef',
        'secondary-fixed-dim': '#bac8d3',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#59666f',
        'on-secondary-fixed': '#101d25',
        'on-secondary-fixed-variant': '#3b4851',
        'tertiary': '#9e3d00',
        'tertiary-container': '#c64f00',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7c2e00',
        'surface': '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#c7dcf7',
        'surface-variant': '#d1e4ff',
        'surface-container': '#e4efff',
        'surface-container-high': '#dae9ff',
        'surface-container-highest': '#d1e4ff',
        'surface-container-low': '#eef4ff',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#0059c7',
        'on-surface': '#071d31',
        'on-surface-variant': '#414755',
        'on-background': '#071d31',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'outline': '#727786',
        'outline-variant': '#c1c6d7',
        'inverse-surface': '#1e3247',
        'inverse-on-surface': '#e9f1ff',
        'inverse-primary': '#afc6ff',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
}
